export const expectedPaths = [
  ['[with-params]', '[with-all]', '[with-direct-all]', 'all.ts'],
  ['[with-params]', '[with-all]', 'all.all.ts'],
  ['[with-params]', '[with-direct]', 'delete.ts'],
  ['[with-params]', '[with-direct]', 'get.ts'],
  ['[with-params]', '[with-direct]', 'head.ts'],
  ['[with-params]', '[with-direct]', 'options.ts'],
  ['[with-params]', '[with-direct]', 'patch.ts'],
  ['[with-params]', '[with-direct]', 'post.ts'],
  ['[with-params]', '[with-direct]', 'put.ts'],
  ['[with-params]', 'delete.delete.ts'],
  ['[with-params]', 'get.get.ts'],
  ['[with-params]', 'head.head.ts'],
  ['[with-params]', 'options.options.ts'],
  ['[with-params]', 'patch.patch.ts'],
  ['[with-params]', 'post.post.ts'],
  ['[with-params]', 'put.put.ts'],
  ['without-params', 'delete.delete.ts'],
  ['without-params', 'get.get.ts'],
  ['without-params', 'head.head.ts'],
  ['without-params', 'options.options.ts'],
  ['without-params', 'patch.patch.ts'],
  ['without-params', 'post.post.ts'],
  ['without-params', 'put.put.ts'],
  ['without-params', 'with-all', 'all.all.ts'],
  ['without-params', 'with-all', 'with-direct-all', 'all.ts'],
  ['without-params', 'with-direct', 'delete.ts'],
  ['without-params', 'with-direct', 'get.ts'],
  ['without-params', 'with-direct', 'head.ts'],
  ['without-params', 'with-direct', 'options.ts'],
  ['without-params', 'with-direct', 'patch.ts'],
  ['without-params', 'with-direct', 'post.ts'],
  ['without-params', 'with-direct', 'put.ts'],
]

export const expectedMethods = {
  '[with-params]/[with-all]/[with-direct-all]/all.ts': {
    method: 'all',
    routeExpress: '/:with-params/:with-all/:with-direct-all',
    route: '',
  },
  '[with-params]/[with-all]/all.all.ts': {
    method: 'all',
    routeExpress: '/:with-params/:with-all/all',
    route: 'all',
  },
  '[with-params]/[with-direct]/delete.ts': {
    method: 'delete',
    routeExpress: '/:with-params/:with-direct',
    route: '',
  },
  '[with-params]/[with-direct]/get.ts': {
    method: 'get',
    routeExpress: '/:with-params/:with-direct',
    route: '',
  },
  '[with-params]/[with-direct]/head.ts': {
    method: 'head',
    routeExpress: '/:with-params/:with-direct',
    route: '',
  },
  '[with-params]/[with-direct]/options.ts': {
    method: 'options',
    routeExpress: '/:with-params/:with-direct',
    route: '',
  },
  '[with-params]/[with-direct]/patch.ts': {
    method: 'patch',
    routeExpress: '/:with-params/:with-direct',
    route: '',
  },
  '[with-params]/[with-direct]/post.ts': {
    method: 'post',
    routeExpress: '/:with-params/:with-direct',
    route: '',
  },
  '[with-params]/[with-direct]/put.ts': {
    method: 'put',
    routeExpress: '/:with-params/:with-direct',
    route: '',
  },
  '[with-params]/delete.delete.ts': {
    method: 'delete',
    routeExpress: '/:with-params/delete',
    route: 'delete',
  },
  '[with-params]/get.get.ts': {
    method: 'get',
    routeExpress: '/:with-params/get',
    route: 'get',
  },
  '[with-params]/head.head.ts': {
    method: 'head',
    routeExpress: '/:with-params/head',
    route: 'head',
  },
  '[with-params]/options.options.ts': {
    method: 'options',
    routeExpress: '/:with-params/options',
    route: 'options',
  },
  '[with-params]/patch.patch.ts': {
    method: 'patch',
    routeExpress: '/:with-params/patch',
    route: 'patch',
  },
  '[with-params]/post.post.ts': {
    method: 'post',
    routeExpress: '/:with-params/post',
    route: 'post',
  },
  '[with-params]/put.put.ts': {
    method: 'put',
    routeExpress: '/:with-params/put',
    route: 'put',
  },
  'without-params/delete.delete.ts': {
    method: 'delete',
    routeExpres: '/without-params/delete',
    route: 'delete',
  },
  'without-params/get.get.ts': {
    method: 'get',
    routeExpres: '/without-params/get',
    route: 'get',
  },
  'without-params/head.head.ts': {
    method: 'head',
    routeExpres: '/without-params/head',
    route: 'head',
  },
  'without-params/options.options.ts': {
    method: 'options',
    routeExpres: '/without-params/options',
    route: 'options',
  },
  'without-params/patch.patch.ts': {
    method: 'patch',
    routeExpres: '/without-params/patch',
    route: 'patch',
  },
  'without-params/post.post.ts': {
    method: 'post',
    routeExpres: '/without-params/post',
    route: 'post',
  },
  'without-params/put.put.ts': {
    method: 'put',
    routeExpres: '/without-params/put',
    route: 'put',
  },
  'without-params/with-all/all.all.ts': {
    method: 'all',
    routeExpres: '/without-params/all',
    route: 'all',
  },
  'without-params/with-all/with-direct-all/all.ts': {
    method: 'all',
    routeExpres: '/without-params/with-all/with-direct-all',
    route: '',
  },
  'without-params/with-direct/delete.ts': {
    method: 'delete',
    routeExpres: '/without-params/with-direct',
    route: '',
  },
  'without-params/with-direct/get.ts': {
    method: 'get',
    routeExpres: '/without-params/with-direct',
    route: '',
  },
  'without-params/with-direct/options.ts': {
    method: 'options',
    routeExpres: '/without-params/with-direct',
    route: '',
  },
  'without-params/with-direct/patch.ts': {
    method: 'patch',
    routeExpres: '/without-params/with-direct',
    route: '',
  },
  'without-params/with-direct/head.ts': {
    method: 'head',
    routeExpres: '/without-params/with-direct',
    route: '',
  },
  'without-params/with-direct/post.ts': {
    method: 'post',
    routeExpres: '/without-params/with-direct',
    route: '',
  },
  'without-params/with-direct/put.ts': {
    method: 'put',
    routeExpres: '/without-params/with-direct',
    route: '',
  },
}
